### ISSUE TITLE
line segmentation hangs on empty pages in 0.5.0

### ISSUE THREAD

**Issue by Wekhrlin** [OCR4all/OCR4all#107]
If I may refer to issue #45 and sort of reopen it: Either this bug is back in 0.5.0 or it never vanished at all. Although the line segmentation is not to be counted as the fastes process of OCR4all, it detects blank pages quite reliable if you let it run for a night or two and then examinate the lines which were not processed... ;-)

Joking aside: Empty pages cause the thread, which tries to process it, to hang, so that all threads of a session can suddenly get stuck on an empty page. In most cases, the docker container has to be restarted to run the line segmentation again with the workaround mentioned in #45 (deselect all empty pages).

**Comment by maxnth** [comment]
Thanks for the bug report. We're aware that the line segmentation in the currently available versions of OCR4all sadly isn't as performant as it could be. Because of that we're working on revising the line segmentation in OCR4all (see: OCR4all_helper_scripts). 
The upcoming release will – among other things – feature a faster line segmentation which should also be more robust against e.g. empty pages.

**Comment by Wekhrlin** [comment]
Thanks for the information. It sounds very promising and I am curious to see the coming developement!

In the meantime I'd like to share my (very quick and dirty – but it works!) Python script to detect blank pages. One only has to change the folder_path. The name of the OCR4all project is called by -p or --project. It uses the binarised files, so the preprocessing should be done.

```
#!/usr/bin/python

import os,glob,cv2,argparse,shutil
from skimage import io


def blank_detection(proj):
    folder_path = '/home/ml/ocr4all/'+proj+'/'
    blank_folder = folder_path+'blank'
    for filename in glob.glob(os.path.join(folder_path+'processing', '*.bin.png')):
        image = io.imread(filename)
        pixels = cv2.countNonZero(image)
        if pixels == 0:
            if os.path.isdir(blank_folder) is False:
                os.mkdir(blank_folder)
            file = filename[-12:-8]
            shutil.move(folder_path+'input/'+file+'.png',blank_folder+'/'+file+'.png')
            print(file+'.png --> ../blank')
            for ext in '.bin.png', '.nrm.png', '.xml':
                try:
                    shutil.move(folder_path+'processing/'+file+ext,blank_folder+'/'+file+ext)
                    print(file+ext,'--> ../blank')
                except:
                    print(file+ext,'not found.')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", "-p", type=str, required=True)
    args = parser.parse_args()
    blank_detection(args.project)


if __name__ == "__main__":
    main()
```
