### ISSUE TITLE
Import external PageXML and image (e.g. from eynollah layout segmentation)

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#112]
I'm trying to import image files and corresponding PageXMLs from eynollah in order to prepare newspaper GT in LAREX. Eynollah's flavour of PageXML is different from what is used in OCR4all for it doesn't contain `TextLine` but rather `TextRegions` which can have an `<TextEquiv>` element

```
 <pc:TextRegion id="region_0001" type="paragraph">
            <pc:Coords points="2470,5622 2470,5623 2621,5623 2621,5622 2593,5622 2592,5623 2575,5623 2574,5622"/>
            <pc:TextEquiv index="0">
                <pc:Unicode></pc:Unicode>
            </pc:TextEquiv>
</pc:TextRegion>
```
(sample jpg and xml can be found [here](https://cloud.uni-halle.de/s/BgvPkRwwuONKTyf)

I have converted the `jpg` into a `bin.png`, renamed the files etc. according to the OCR4all requirements and am happy to see that it kind of works. There seems to be an issue, however, with the page geometry (apart from fiddling about image conversion and renaming, which probably have to be undone when re-exporting back the files into the original project folder). The coordinates appear to refer to different image dimensions and result in much bigger boarders:

![Screenshot_2021-06-03 Larex - Editor](https://user-images.githubusercontent.com/52370148/120605542-72f3b700-c44e-11eb-9fec-037bec840e6f.png)

I guess I could scale down the coordinates or scale up the images (`convert -resize` + image dimensions from the pagexml do the job, in fact), but maybe you have a better idea as to how to integrate OCR4all in a workflow where external image and pagexml are used.

Thanks!

**Comment by alexander-winkler** [comment]
Maybe the different scales have to do with an image enhancement eynollah undertakes (`-ae` option). It writes the new dimensions to the pagexml but doesn't change the original image file (https://github.com/qurator-spk/eynollah). I guess that's the problem.

**Comment by maxnth** [comment]
I just wanted to ask whether the sample jpg files are the original input for eynollah as the PAGE XML has other height / width attribute values then the images themselves :sweat_smile: 
We might check for that during loading images (whether image dimensions fit to the PAGE XML dimensions and resize the image accordingly) but as I guess this is more of an edge case it might not be included in the next release.

**Comment by kba** [comment]
> Maybe the different scales have to do with an image enhancement eynollah undertakes (`-ae` option). It writes the new dimensions to the pagexml but doesn't change the original image file (https://github.com/qurator-spk/eynollah). I guess that's the problem.

Exactly, the `--allow-enhancement` option will use the coordinates of the enhanced/scaled image. In the standalone eynollah CLI you can replace the original image with the enhanced image that should be written out with `-ae`. In the OCR-D interface, we removed the `--allow-enhancement` parameter in [v0.0.5](https://github.com/qurator-spk/eynollah/releases/tag/v0.0.5) so coordinates are always for the original image.

**Comment by kba** [comment]
> We might check for that during loading images (whether image dimensions fit to the PAGE XML dimensions and resize the image accordingly) but as I guess this is more of an edge case it might not be included in the next release.

Unless it's a rounding error (like 1 pixel difference between `identify -format '%w %h'` and `@imageWidth`/`@imageHeight`), I would not try to mitigate this, because it would be an obvious error in the preprocessing.
