### ISSUE TITLE
Initialization of the container

### ISSUE THREAD

**Issue by wilcar** [OCR4all/OCR4all#120]
Hello,
I'm new to docker. I have installed docker desktop for windows 10.
I downloaded the docker image but I don't know how to initialize it
Here is what docker offers me as options. Your document is unclear for me !
Thanks for your help.

![image](https://user-images.githubusercontent.com/18226229/134797678-c3db2e00-b140-4fd1-a41c-7a1a42fb6e77.png)

![image](https://user-images.githubusercontent.com/18226229/134797692-63330829-da91-41bd-ad94-8e9251ef133b.png)

**Comment by L-FL** [comment]
Hi wilcar,
have you already executed the "run"-command?
you can either paste the command from the [calls.txt](https://github.com/OCR4all/getting_started/blob/master/calls.txt) below into PowerShell (docker must be running of course)
or
enter the respective info into the fields in your first screenshot and then click "run".

By the way, normally on Windows you never need to open the Docker app or do anything with it. Starting the container via the shell using `docker start -ia ocr4all` is quite sufficient.
