### ISSUE TITLE
page export does not seem to include TextLine reading order

### ISSUE THREAD

**Issue by jeffreycwitt** [OCR4all/OCR4all#155]
I'm not sure if this is an issue or question, but if I add TextLines in Larex and then change or adjust their reading order, I don't see that reading order reflected in the exported page file. 

In the xml files, the newly created TextLine (whatever their proper reading order) are "appended" at the bottom of the containing text region. 

But there doesn't seem to be anything in the file that I can use to place them in their correct reading order. 

This is different than what I see for Text Regions. While the Text Region position in the XML also don't reflect the proper reading order, the exported file always includes a reading order block that I can use to arrange the text in the proper reading order (See below)

```
  <ReadingOrder>
      <OrderedGroup id="g2">
        <RegionRefIndexed index="0" regionRef="r1"/>
        <RegionRefIndexed index="1" regionRef="r2"/>
      </OrderedGroup>
    </ReadingOrder>
```

But there doesn't seem to be such a ReadingOrder block for TextLines.

I could easily be doing something wrong or missing something. So, I am most grateful for any advice.

**Comment by jeffreycwitt** [comment]
Ok. I think that fixed it. Many thanks. I'll close it now.

**Comment by alexander-winkler** [comment]
Not sure if my issue belongs here. I've just pulled the latest docker image (LAREX: v0.7.3) and manually split up a double line into two single lines. A text line element `<TextLine id="r0_l019">` was converted into `<TextLine id="l26">` and `<TextLine id="l27">`. These were appended to the end of the `<TextRegion>` node and not at the position of the defined reading order. LAREX still manages to guess the correct reading order (how I cannot fathom), but it can no longer be derived from the PageXML. This is unfortunate as I am doing some script-based post correction and quality control that gets messed up without the correct reading order. Is there anything I can do or don't get? Thanks!
