### ISSUE TITLE
Using calamari models in OCR4all 

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#16]
Hello!
I have trained a calamari model using the `calamari-train` (v0.3.5) command. Since I'd like to use OCR4all in order to keep track of the project I tried to copy the model into the ocr4 models-directory
```
project/
└── 0
    ├── 0.ckpt.data-00000-of-00001
    ├── 0.ckpt.index
    ├── 0.ckpt.json
    ├── 0.ckpt.meta
    ├── checkpoint
```

During the recognition process I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py", line 547, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py", line 552, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse network field: Failed to parse backend field: Message type "BackendParams" has no field named "shuffleBufferSize".
 Available Fields(except extensions): 
```
Is there a way to use externally trained models in OCR4all?
Thanks in advance!

**Comment by ChWick** [comment]
OCR4all currently uses an older version of Calamari (v0.3.3) which is why models trained with the newer version (v0.3.5) can not be used with OCR4all. You have three options:
* Downgrade calamari to v0.3.3
* Wait for OCR4all to upgrade Calamari to v0.3.5
* "Hack your model" by removing the `shuffleBufferSize` field in your `0.ckpt.json` file

**Comment by NesbiDevelopment** [comment]
It is noteworthy that OCR4all `stable` uses calamari v0.3.3.
`nightly` and `dev` use the newest calamari version.
But we are currently working on creating a new stable version which will include the new calamari version.

It is possible to pull the `nightly` or `dev` version from docker hub.
```docker pull ls6uniwue/ocr4all:<tag_name>```

But we'd recommend waiting for the next stable release, that is planned to arrive shortly.

**Comment by NesbiDevelopment** [comment]
The stable release includes this fix

**Comment by maxnth** [comment]
Calamari >1.0 uses TensorFlow 2.x (compared to TensorFlow 1.x in the previous versions) and the weights couldn't be converted (a more detailed explanation can be found [here](https://github.com/Calamari-OCR/calamari_models/issues/4#issuecomment-610970725))
This sadly means that models which were e.g. trained with calamari 0.3.5 can't be used with current calamari versions and therefore also not with current OCR4all versions.

**Comment by maxnth** [comment]
Addendum:
To help easing the transition from older calamari / OCR4all versions to newer ones we currently offer to retrain models with an up-to-date calamari version on our GPU server.
