### ISSUE TITLE
line segmentation hangs on empty pages

### ISSUE THREAD

**Issue by khe29** [OCR4all/OCR4all#45]
The line segmentation workflow step hangs on empty pages. As a workaround it is possible to deselect empty pages before the workflow is started, but it would be good, if this could be fixed.

**Comment by chreul** [comment]
thx for the hint and sorry for the late reply. we are quite busy at the moment but will look into it as soon as possible.

**Comment by khe29** [comment]
With OCR4all version 0.3.0 the problem seems to be gone. I think this problem report may be closed.

**Comment by maxnth** [comment]
Thanks for your hint.
I couldn't reproduce the bug in newer versions either.
