### ISSUE TITLE
Pixel classifier for page segmentation

### ISSUE THREAD

**Issue by jeanm** [OCR4all/OCR4all#47]
I see some mentions here and there, including in the code, of a trainable pixel classifier for page segmentation. Is this available to try? I have a document where LAREX automatic segmentation performs quite poorly.

**Comment by chreul** [comment]
there are several ongoing projects but unfortunately i'm not sure which one is the most promising at the moment. some places to start looking:
- https://gitlab2.informatik.uni-wuerzburg.de/ls6/page-segmentation (connected to the [OCR-D](https://github.com/OCR-D) project)
- https://github.com/qurator-spk
- https://github.com/dhlab-epfl/dhSegment
