### ISSUE TITLE
Add filter to "Select All" function

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#49]
Hello!

When OCR'ing, e.g., bilingual editions it would be nice if I could handle left and right pages separately or in other cases I might find it useful to select but a part of the book for training. Selecting the pages one by one is, of course, not really an option if it comes to larger books. So I was wondering if you might consider adding a filter function to the "select" tool in the column on the right. It would be great to have an syntax that allows to select multiple ranges (optionally with modulo).

Or is there any other recommended way to deal with such cases (apart from messing with the input data)?

Many thanks!

**Comment by maxnth** [comment]
We're already planning to add more advanced filtering features to the page selector in one of the upcoming releases and your proposal sounds very reasonable and useful.
We'll look into it and hope to add it in one of the upcoming releases.

**Comment by maxnth** [comment]
The ability to switch between the selection modes `all`, `even` and `odd` was added to the image list in the sidebar and will be featured in the next release.
