### ISSUE TITLE
How to deal with marginalia

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#50]
Hello! I'm not sure if a github issue is the right place to ask, so please bear with me.

I often get segmentation results of the following type:
![Screenshot from 2020-02-25 08-55-39](https://user-images.githubusercontent.com/52370148/75226769-321de480-57ad-11ea-83e8-3aeb10dd2849.png)

Line segmentation work perfectly, but the results are compromised by the marginalia. One work-around to get rid of them would be, I guess, to grab the x-maxima from the Page XML and replace them with the average x-values of the page. However, this method is far from optimal as it ignore whitespaces etc.

Is there any way to deal with marginalia apart from adjusting every line/every page in LAREX?

Thank you so much!

**Comment by maxnth** [comment]
Please excuse the late reply.

At the moment this is only possible using the semi-automatic workflow provided by Larex.
Adjusting the `Text Dilation` parameter (especially lowering the x value) in Larex should help you to separate marginalia and the paragraph (in case the spacing between marginalia and paragraphs stays roughly the same on all pages of the book).

#### Example:
Using default text dilation values
![standard_text_dilation](https://user-images.githubusercontent.com/33344081/75820413-98ea6180-5d9c-11ea-9e31-eb8b4aa2bbdf.png)
Using slightly adjusted text dilation values
![changed_text_dilation](https://user-images.githubusercontent.com/33344081/75820510-c1725b80-5d9c-11ea-917f-f7add38001b2.png)

If you plan to not consider marginalia at all during the layout segmentation setting a global `ignore rectangle` (or several in case of different recto and verso layouts) afterwards should help to achieve that.  

We're already planning to integrate a fully automatic layout segmentation into OCR4all so if the semi-automatic workflow isn't suitable for your use case, using OCR4all for this task may be an option for you in the (near) future.

**Comment by alexander-winkler** [comment]
As always, I'm stunned both by your project and your support, thank you very much! 

I've tried the Text Dilation method on my material, but it doesn't result in the desired output (I loose some of the main text when lowering the x value of the Text Dilation)

I'm looking obviously forward to the next version of OCR4all; is it right that as of now there is no way to batch process, say, an entire book with the global `ignore rectangle` option?

**Comment by maxnth** [comment]
>is it right that as of now there is no way to batch process, say, an entire book with the global ignore rectangle option?

You're right, this isn't actually possible yet.

Considering that such an option might save a lot of time in some use cases we'll look into adding this option as soon as we find time for it.
