### ISSUE TITLE
Persistent TextLine-IDs in PageXML

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#53]
I'm working on the pageXML files created with OCR4all in a different context and found it inconvenient that the TextLines cannot persistently be addressed as every time I save a new pageXML in LAREX new TextLine-ids are given to the elements. If I'm not mistaken, there is no need for them to be numbered in an ascending order (l1,l2,l3 ..., ln), even arbitrary ids could be used. These would be less readable, of course, but they would facilitate the reuse of the data.

**Comment by maxnth** [comment]
In cases where no text lines where deleted, drastically changed (coordinatewise) or added before/inbetween existing lines the line ID normally shouldn't change, as numbering in ascending order should still yield the same result (if I'm not overlooking something).
In other cases I'm not sure whether one would be able to promise persistent line IDs as in certain cases it may be difficult to determine which newly generated/altered line resembles the line from the "previous" version.

In case I'm missing the point or overlooking something obvious, I apologize for that.
