### ISSUE TITLE
Undo GT input in LAREX

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#57]
Hello! One functionality that might come in handy in LAREX would be to undo GT input. When GT input is done mistakenly (and the field turns green) , it is of course possible to try the undo function but I guess it'd be probably a cleaner solution if there were also a proper "delete GT in this field" function.

**Comment by maxnth** [comment]
Thanks for the suggestion., sadly we didn't get to implement this yet but it's already on our [bucket list](https://github.com/OCR4all/LAREX/issues/145) for LAREX/GTP enhancements.

**Comment by maxnth** [comment]
This feature was added to the dev branch of LAREX and will most likely available in version 0.5 of the OCR4all docker release
