### ISSUE TITLE
PDF to image conversion can cause OutOfMemoryError

### ISSUE THREAD

**Issue by maxnth** [OCR4all/OCR4all#59]
When converting very large PDF files (e.g. with >7000 pages) to images in the `Project Overview` OCR4all may throw an OutOfMemoryError.
This could be avoided by either breaking down the PDF into smaller chunks are streaming the file instead of loading the whole file at once.

**Comment by khe29** [comment]
There is also an OutOfMemory problem, if there are about 80 PDF files with 35-40 pages in average are processed in sequence with the automatic workflow. The problem occurs each time, when such a number of PDFs is processed.
Restarting the OCR4all docker container fixes the problem temporarily, until the next 80-90 PFDs are processed.
As a workaround I had to break my processing workflow into smaller steps with around 70 PDFs and restart the docker container inbetween to avoid the error. For proccessing of a larger number of PDF files this is a nuisance.

Best regards,
  Karlheinz Eckmeier

**Comment by maxnth** [comment]
This issue should be fixed in [release 0.3.0](https://github.com/OCR4all/OCR4all/releases/tag/0.3.0).
If the problem still persists with the use case you @khe29 described above or any other use case involving PDFs you might come upon, please let us now.
