### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Lawksie** [OCR4all/OCR4all#63]
I used OCR4all with great success on my previous laptop, but cannot get it installed and running on the new laptop.

Unable to get the advanced Settings options.

Command line error.

Web interface not working.

![dockerexpected](https://user-images.githubusercontent.com/66214363/83357909-6504e500-a367-11ea-9b32-9d05e43a387a.jpg)
![OCR4AllCommanline](https://user-images.githubusercontent.com/66214363/83357910-66cea880-a367-11ea-84db-d438f9fbcd40.jpg)
![ocr4allweb](https://user-images.githubusercontent.com/66214363/83357911-67ffd580-a367-11ea-86e2-c6aa386c69f4.jpg)

**Comment by maxnth** [comment]
We moved the "location" of OCR4all webapp in the latest docker image from `OCR4all_Web` to `ocr4all`.
Opening `localhost:1476/ocr4all` in your browser should let you access OCR4all.
 
Just opening `localhost:1476` will also open a landing page which let's you select either OCR4all oder LAREX by clicking on a the corresponding link.

**Comment by Lawksie** [comment]
This is fantastic. Thank you so much. I've spent a frustrating 9 hours on it today. Thank you again! L
