### ISSUE TITLE
Use GT for result production

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#69]
As a follow-up on #68 , I'd also suggest to add an option to "Result Generation" that allows you to use GT where available. As of now, I exports the OCR even if there is there is already a manually corrected version of the line.

**Comment by maxnth** [comment]
Usually GT (as in `TextEquiv` elements with `@index="0"`) should already be prioritized over recognized text (as in `TextEquiv` elements with `@index="1"`) during the text result generation.
I just tested it with the following text line:
![gt](https://user-images.githubusercontent.com/33344081/86455708-4bb5d680-bd21-11ea-9672-ab5468be2a63.png)
The associated line in the generated text result does indeed show "Test" in my test case.

Can you confirm that the behavior described in your issue occurs? If yes, could you maybe send us a PAGE XML file where it occurs?

**Comment by alexander-winkler** [comment]
I am sorry, I hadn't noticed that the result folder gets timestamped now, so I got always referred to an outdated version.
