### ISSUE TITLE
Training subprocesses crash

### ISSUE THREAD

**Issue by jeanm** [OCR4all/OCR4all#70]
I am training a recognition model using my own GT, using the latest OCR4all docker image on macOS Catalina. Training starts fine, but no matter what I do one or more fold subprocesses appear to crash. I can tell because they stop outputting to the console.

For example, this is a training run with a 3-fold model, trained from scratch, with early stopping set to 3, batch size set to 1, and all other params set to the default. After this point, `FOLD 1` goes silent and only `0` and `2` keep reporting:
```
FOLD 0 | #00000400: loss=69.85398586 ler=0.83131579 dt=2.73654627s
FOLD 0 |   PRED: '‪cde l' o ae atalipio‬'
FOLD 0 |   TRUE: '‪cheu l'è o mæ nataliçio!‬'
FOLD 2 | #00000400: loss=87.79671794 ler=0.81507108 dt=2.92006311s
FOLD 2 |   PRED: '‪, i ella va iase l'ppsiie ationar‬'
FOLD 2 |   TRUE: '‪1815-1877), in quella nuova fase l'opposizione antimonar-‬'
FOLD 1 | #00000450: loss=52.99123604 ler=0.72493431 dt=2.78957310s
FOLD 1 |   PRED: '‪cenni del see. e poi ripresi nell'inediato secondo do-‬'
FOLD 1 |   TRUE: '‪cenni del sec. XX e poi ripresi nell'immediato secondo do-‬'
```
I can tell, from the update time attribute of the file system, that the checkpoints are no longer being saved for fold 1, so I assume the process has just crashed.

I have tried a bunch of different settings: leaving all params to the default (5-fold, batch size 4), training from scratch, training from one of the provided models, reducing batch size to 1 and #folds to 3 (as I suspected an OOM might be causing the crashes), freeing up as much RAM as possible on my system, but there's always one or more folds that disappear. Training is always on CPU. There are no errors in the console. The surviving subprocesses continue training fine, and achieve good performance.

Sometimes the subprocesses stop reporting right at the start, before they even start training, sometimes it happens during validation, and sometimes (like in the example above) it seems to happen during training.

Any idea what might be going on?

**Comment by jeanm** [comment]
As a follow-up, I exported the GT from OCR4all using the exporting feature on the main page, and managed to successfully train an _n_-fold model directly using the Calamari command-line interface (installed via `pip install`). I then copied the trained models back into OCR4all's folder structure, and I was able to use them successfully for predicting.

Therefore, it seems that the issue might be due to either the specific version of Calamari that's bundled with the Docker image, or perhaps some weird interaction between Python's multiprocessing and Docker.

**Comment by maxnth** [comment]
Thank you very much for the follow-up and excuse the late reply.
Sadly we didn't get to investigate this bug yet but we'll look into it as soon as possible.

**Comment by jeanm** [comment]
No worries at all! This isn't blocking me – I have a workaround 😊

**Comment by maxnth** [comment]
Closing this in the hope that the problem doesn't persist with newer OCR4all / Calmari versions.
